Repository SpecialTeam01/JavaSpacialTeam, pull requests merged in 2025-05, with the labels that each got.

#11 Develop kenny front astronautas
  src/main/webapp/css/styles.css
  src/main/webapp/includes/footer.jsp
  src/main/webapp/index.jsp
  src/main/webapp/jsp/astronaut-detail.jsp
  src/main/webapp/jsp/astronaut-form.jsp
  src/main/webapp/jsp/astronaut-list.jsp
Labels: enhancement

#12 Missions Frontend review
  src/main/java/servlet/MissionServlet.java
  src/main/webapp/jsp/mission-details.jsp
  src/main/webapp/jsp/mission-form.jsp
  src/main/webapp/jsp/mission-list.jsp
Labels: enhancement

#14 Visual enhancements of form pages and buttons
  src/main/webapp/css/styles.css
  src/main/webapp/includes/footer.jsp
  src/main/webapp/jsp/astronaut-form.jsp
  src/main/webapp/jsp/astronaut-list.jsp
  src/main/webapp/jsp/mission-form.jsp
  src/main/webapp/jsp/mission-list.jsp
  src/main/webapp/jsp/planet-list.jsp
Labels: enhancement

#15 Pagination in missions and animation
  src/main/java/servlet/MissionServlet.java
  src/main/webapp/css/animacion.css
  src/main/webapp/images/Animation.json
  src/main/webapp/images/fondomision.png
  src/main/webapp/includes/animacion.jsp
  src/main/webapp/includes/header.jsp
  src/main/webapp/jsp/mission-list.jsp
Labels: enhancement

#16 Develop miguel buscador
  src/main/java/dao/AstronautDAO.java
  src/main/java/dao/MissionDAO.java
  src/main/java/dao/PlanetDAO.java
  src/main/java/servlet/SearchServlet.java
  src/main/webapp/index.jsp
Labels: enhancement

#18 Images add
  src/main/java/servlet/AstronautServlet.java
  src/main/webapp/images/default.png
  src/main/webapp/jsp/astronaut-detail.jsp
Labels: enhancement, good first issue

#19 Modificación de algunos estilos para el fondo de imagen de las pagina…
  src/main/webapp/css/styles.css
  src/main/webapp/jsp/astronaut-detail.jsp
  src/main/webapp/jsp/mission-detail.jsp
  src/main/webapp/jsp/mission-form.jsp
  src/main/webapp/jsp/planet-form.jsp
Labels: bug, enhancement

#20 Corrected errors in styles applied to the body and visually improved …
  src/main/webapp/css/styles.css
  src/main/webapp/jsp/mission-list.jsp
Labels: bug, enhancement

#21 Final development to visualize images of planets.
  Consulta.sql
  src/main/java/servlet/PlanetServlet.java
  src/main/webapp/images/Kepler-186f.png
  src/main/webapp/images/Proxima-Centauri-b.png
  src/main/webapp/images/europa.png
  src/main/webapp/images/mars.png
  src/main/webapp/images/titan.png
  src/main/webapp/jsp/planet-detail.jsp
Labels: enhancement

#24 Develop nerea sql
  Consulta.sql
Labels: bug
